Sound = {};
Sound._notes = {
  0: {
    "C"  : { "frequency" : "16.35",   "wavelength" : "2100" },
    "C#" : { "frequency" : "17.32",   "wavelength" : "1990" },
    "Db" : { "frequency" : "17.32",   "wavelength" : "1990" },
    "D"  : { "frequency" : "18.35",   "wavelength" : "1870" },
    "D#" : { "frequency" : "19.45",   "wavelength" : "1770" },
    "Eb" : { "frequency" : "19.45",   "wavelength" : "1770" },
    "E"  : { "frequency" : "20.60",   "wavelength" : "1670" },
    "F"  : { "frequency" : "21.83",   "wavelength" : "1580" },
    "F#" : { "frequency" : "23.12",   "wavelength" : "1490" },
    "Gb" : { "frequency" : "23.12",   "wavelength" : "1490" },
    "G"  : { "frequency" : "24.50",   "wavelength" : "1400" },
    "G#" : { "frequency" : "25.96",   "wavelength" : "1320" },
    "Ab" : { "frequency" : "25.96",   "wavelength" : "1320" },
    "A"  : { "frequency" : "27.50",   "wavelength" : "1250" },
    "A#" : { "frequency" : "29.14",   "wavelength" : "1180" },
    "Bb" : { "frequency" : "29.14",   "wavelength" : "1180" },
    "B"  : { "frequency" : "30.87",   "wavelength" : "1110" }
  },
  1: {
    "C"  : { "frequency" : "32.70",   "wavelength" : "1050" },
    "C#" : { "frequency" : "34.65",   "wavelength" : "996"  },
    "Db" : { "frequency" : "34.65",   "wavelength" : "996"  },
    "D"  : { "frequency" : "36.71",   "wavelength" : "940"  },
    "D#" : { "frequency" : "38.89",   "wavelength" : "887"  },
    "Eb" : { "frequency" : "38.89",   "wavelength" : "887"  },
    "E"  : { "frequency" : "41.20",   "wavelength" : "837"  },
    "F"  : { "frequency" : "43.65",   "wavelength" : "790"  },
    "F#" : { "frequency" : "46.25",   "wavelength" : "746"  },
    "G#" : { "frequency" : "46.25",   "wavelength" : "746"  },
    "G"  : { "frequency" : "49.00",   "wavelength" : "704"  },
    "G#" : { "frequency" : "51.91",   "wavelength" : "665"  },
    "Ab" : { "frequency" : "51.91",   "wavelength" : "665"  },
    "A"  : { "frequency" : "55.00",   "wavelength" : "627"  },
    "A#" : { "frequency" : "58.27",   "wavelength" : "592"  },
    "Bb" : { "frequency" : "58.27",   "wavelength" : "592"  },
    "B"  : { "frequency" : "61.74",   "wavelength" : "559"  }
  },
  2: {
    "C"  : { "frequency" : "65.41",   "wavelength" : "527"  },
    "C#" : { "frequency" : "69.30",   "wavelength" : "498"  },
    "Db" : { "frequency" : "69.30",   "wavelength" : "498"  },
    "D"  : { "frequency" : "73.42",   "wavelength" : "470"  },
    "D#" : { "frequency" : "77.78",   "wavelength" : "444"  },
    "Eb" : { "frequency" : "77.78",   "wavelength" : "444"  },
    "E"  : { "frequency" : "82.41",   "wavelength" : "419"  },
    "F"  : { "frequency" : "87.31",   "wavelength" : "395"  },
    "F#" : { "frequency" : "92.50",   "wavelength" : "373"  },
    "Gb" : { "frequency" : "92.50",   "wavelength" : "373"  },
    "G"  : { "frequency" : "98.00",   "wavelength" : "352"  },
    "G#" : { "frequency" : "103.83",  "wavelength" : "332"  },
    "Ab" : { "frequency" : "103.83",  "wavelength" : "332"  },
    "A"  : { "frequency" : "110.00",  "wavelength" : "314"  },
    "A#" : { "frequency" : "116.54",  "wavelength" : "296"  },
    "Bb" : { "frequency" : "116.54",  "wavelength" : "296"  },
    "B"  : { "frequency" : "123.47",  "wavelength" : "279"  }
  },
  3: {
    "C"  : { "frequency" : "130.81",  "wavelength" : "264"  },
    "C#" : { "frequency" : "138.59",  "wavelength" : "249"  },
    "Db" : { "frequency" : "138.59",  "wavelength" : "249"  },
    "D"  : { "frequency" : "146.83",  "wavelength" : "235"  },
    "D#" : { "frequency" : "155.56",  "wavelength" : "222"  },
    "Eb" : { "frequency" : "155.56",  "wavelength" : "222"  },
    "E"  : { "frequency" : "164.81",  "wavelength" : "209"  },
    "F"  : { "frequency" : "174.61",  "wavelength" : "198"  },
    "F#" : { "frequency" : "185.00",  "wavelength" : "186"  },
    "Gb" : { "frequency" : "185.00",  "wavelength" : "186"  },
    "G"  : { "frequency" : "196.00",  "wavelength" : "176"  },
    "G#" : { "frequency" : "207.65",  "wavelength" : "166"  },
    "Ab" : { "frequency" : "207.65",  "wavelength" : "166"  },
    "A"  : { "frequency" : "220.00",  "wavelength" : "157"  },
    "A#" : { "frequency" : "233.08",  "wavelength" : "148"  },
    "Bb" : { "frequency" : "233.08",  "wavelength" : "148"  },
    "B"  : { "frequency" : "246.94",  "wavelength" : "140"  }
  },
  4: {
    "C"  : { "frequency" : "261.63",  "wavelength" : "132"  },
    "C#" : { "frequency" : "277.18",  "wavelength" : "124"  },
    "Db" : { "frequency" : "277.18",  "wavelength" : "124"  },
    "D"  : { "frequency" : "293.66",  "wavelength" : "117"  },
    "D#" : { "frequency" : "311.13",  "wavelength" : "111"  },
    "Eb" : { "frequency" : "311.13",  "wavelength" : "111"  },
    "E"  : { "frequency" : "329.63",  "wavelength" : "105"  },
    "F"  : { "frequency" : "349.23",  "wavelength" : "98.8" },
    "F#" : { "frequency" : "369.99",  "wavelength" : "93.2" },
    "Gb" : { "frequency" : "369.99",  "wavelength" : "93.2" },
    "G"  : { "frequency" : "392.00",  "wavelength" : "88.0" },
    "G#" : { "frequency" : "415.30",  "wavelength" : "83.1" },
    "Ab" : { "frequency" : "415.30",  "wavelength" : "83.1" },
    "A"  : { "frequency" : "440.00",  "wavelength" : "78.4" },
    "A#" : { "frequency" : "466.16",  "wavelength" : "74.0" },
    "Bb" : { "frequency" : "466.16",  "wavelength" : "74.0" },
    "B"  : { "frequency" : "493.88",  "wavelength" : "69.9" }
  },
  5: {
    "C"  : { "frequency" : "523.25",  "wavelength" : "65.9" },
    "C#" : { "frequency" : "554.37",  "wavelength" : "62.2" },
    "Db" : { "frequency" : "554.37",  "wavelength" : "62.2" },
    "D"  : { "frequency" : "587.33",  "wavelength" : "58.7" },
    "D#" : { "frequency" : "622.25",  "wavelength" : "55.4" },
    "Eb" : { "frequency" : "622.25",  "wavelength" : "55.4" },
    "E"  : { "frequency" : "659.26",  "wavelength" : "52.3" },
    "F"  : { "frequency" : "698.46",  "wavelength" : "49.4" },
    "F#" : { "frequency" : "739.99",  "wavelength" : "46.6" },
    "Gb" : { "frequency" : "739.99",  "wavelength" : "46.6" },
    "G"  : { "frequency" : "783.99",  "wavelength" : "44.0" },
    "G#" : { "frequency" : "830.61",  "wavelength" : "41.5" },
    "Ab" : { "frequency" : "830.61",  "wavelength" : "41.5" },
    "A"  : { "frequency" : "880.00",  "wavelength" : "39.2" },
    "A#" : { "frequency" : "932.33",  "wavelength" : "37.0" },
    "Bb" : { "frequency" : "932.33",  "wavelength" : "37.0" },
    "B"  : { "frequency" : "987.77",  "wavelength" : "34.9" }
  },
  6: {
    "C"  : { "frequency" : "1046.50", "wavelength" : "33.0" }
  }
};

Sound._chords = {
  'A'     : ['A', 'C#', 'E'],
  'Am'    : ['A', 'C', 'E'],
  'Bb'    : ['Bb', 'D', 'F'],
  'Bbm'   : ['Bb', 'Db', 'F'],
  'B'     : ['B', 'D#', 'F#'],
  'Bm'    : ['B', 'D', 'F#'],
  'Bdim'  : ['B', 'D', 'F'],
  'C'     : ['C', 'E', 'G'],
  'Cm'    : ['C', 'Em', 'G'],
  'C#'    : ['C#', 'E#', 'G#'],
  'C#m'   : ['C#', 'E', 'G#'],
  'C#dim' : ['C#', 'E', 'G'],
  'Db'    : ['Db', 'F', 'Ab'],
  'Dbm'   : ['Db', 'Fb', 'Ab'],
  'D'     : ['D', 'F#', 'A'],
  'Dm'    : ['D', 'F', 'A'],
  'D#'    : ['D#', 'F#', 'A#'],
  'D#m'   : ['D#', 'F', 'A#'],
  'Eb'    : ['Eb', 'G', 'Bb'],
  'Ebm'   : ['Eb', 'Gb', 'Bb'],
  'E'     : ['E', 'G#', 'B'],
  'Em'    : ['E', 'G', 'B'],
  'Edim'  : ['E', 'G', 'Bb'],
  'F'     : ['F', 'A', 'C'],
  'Fm'    : ['F', 'Ab', 'C'],
  'F#'    : ['F#', 'A#', 'C#'],
  'F#m'   : ['F#', 'A', 'C#'],
  'F#dim' : ['F#', 'A', 'C'],
  'Gb'    : ['Gb', 'Bb', 'Db'],
  'Gbm'   : ['Gb', 'Bbb', 'Db'],
  'G'     : ['G', 'B', 'D'],
  'Gm'    : ['G', 'Bb', 'D'],
  'G#'    : ['G#', 'B#', 'D#'],
  'G#dim' : ['G#', 'B', 'D']
};

Sound._keys = {
  'A' : {
    'A' : Sound._chords['A'],
    'B' : Sound._chords['Bm'],
    'C' : Sound._chords['C#m'],
    'D' : Sound._chords['D'],
    'E' : Sound._chords['E'],
    'F' : Sound._chords['F#m'],
    'G' : Sound._chords['G#dim']
  },
  'B' : {
    'B' : Sound._chords['B'],
    'C' : Sound._chords['C#m'],
    'D' : Sound._chords['D#m'],
    'E' : Sound._chords['E'],
    'F' : Sound._chords['F#'],
    'G' : Sound._chords['G#m'],
    'A' : Sound._chords['A#dim']
  },
  'C' : {
    'C' : Sound._chords['C'],
    'D' : Sound._chords['Dm'],
    'E' : Sound._chords['Em'],
    'F' : Sound._chords['F'],
    'G' : Sound._chords['G'],
    'A' : Sound._chords['Am'],
    'B' : Sound._chords['Bdim']
  },
  'D' : {
    'D' : Sound._chords['D'],
    'E' : Sound._chords['Em'],
    'F' : Sound._chords['F#m'],
    'G' : Sound._chords['G'],
    'A' : Sound._chords['A'],
    'B' : Sound._chords['Bm'],
    'C' : Sound._chords['C#dim']
  },
  'E' : {
    'E' : Sound._chords['E'],
    'F' : Sound._chords['F#m'],
    'G' : Sound._chords['G#m'],
    'A' : Sound._chords['A'],
    'B' : Sound._chords['B'],
    'C' : Sound._chords['C#m'],
    'D' : Sound._chords['D#dim']
  },
  'F' : {
    'F' : Sound._chords['F'],
    'G' : Sound._chords['Gm'],
    'A' : Sound._chords['Am'],
    'B' : Sound._chords['Bb'],
    'C' : Sound._chords['C'],
    'D' : Sound._chords['Dm'],
    'E' : Sound._chords['Edim']
  },
  'G' : {
    'G' : Sound._chords['G'],
    'A' : Sound._chords['Am'],
    'B' : Sound._chords['Bm'],
    'C' : Sound._chords['C'],
    'D' : Sound._chords['D'],
    'E' : Sound._chords['Em'],
    'F' : Sound._chords['F#dim']
  }
}
